import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './../styles/global.css';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Plataforma CAE',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className={`${geistSans.className} ${geistMono.className}`}>
      <body suppressHydrationWarning className="min-h-screen bg-gray-100">
        {children}
      </body>
    </html>
  );
}
